### ISSUE TITLE
Highlight Program slider isn't working in these 4 pages!

### ISSUE THREAD

**Issue by muhammadabir64** [developershakil2/ufbdfrontend#1]
volunteer.html
event.html
zakat_calc.html
img_gallery.html
![image](https://user-images.githubusercontent.com/51321911/156725216-0e7e57c9-8fb8-405b-86b3-8e43bb134f4f.png)

**Comment by developershakil2** [comment]
Okay I'm checking it

**Comment by muhammadabir64** [comment]
thank you brother

**Comment by developershakil2** [comment]
you are welcome brother check in master branch i was updated all and everything fixes 
if you will find any issues then don't forget to let me know

**Comment by developershakil2** [comment]
you are welcome brother check in master branch i was updated all and everything fixes 
if you will find any issues then don't forget to let me know

**Comment by developershakil2** [comment]
you are welcome brother check in master branch i was updated all and everything fixes 
if you will find any issues then don't forget to let me know

**Comment by muhammadabir64** [comment]
okay, thanks again.....

**Comment by developershakil2** [comment]
you're welcome  bro
